import '../img/svg-sprite/icon-angle-down-light.svg'
import '../img/svg-sprite/icon-telegram.svg'
import '../img/svg-sprite/icon-whatsapp.svg'
import '../img/svg-sprite/icon-arrow-right.svg'
import '../img/svg-sprite/icon-angle-down-light-big.svg'
import '../img/svg-sprite/icon-send.svg'
import '../img/svg-sprite/icon-edit.svg'
